Origin/search and pagination updates
marxism/marxist.space pull request #99
Opened 2022-08-28 17:35 UTC by m-ox

# Change Type

* [X] Feature
* [X] Chore
* [ ] Bug Fix

# Change Level

* [X] major
* [ ] minor
* [ ] patch

# Further Information (screenshots, bug report links, etc.)

Aesthetic change
https://gyazo.com/ffe2235e489371198310b6544c479828

# Checklist

* [ ] Tested in supported environments (common browsers)

2022-09-02 01:10 UTC, zacanger requested changes
Thanks for the PR! I have a couple of comments and obviously you have it marked as a draft. I really appreciate the contributions :)

2022-09-02 01:10 UTC, zautumnz commented on index.html
> +      document.getElementById("scroll-top").onclick = function() {window.scrollTo(0, 0);}
```suggestion
      document.getElementById("scroll-top").onclick = () => { window.scrollTo(0, 0) }
```

This project prefers ES2015+ syntax and no semicolons :)

2022-09-02 01:10 UTC, zautumnz commented on script.js
> +   enrichResources = (resources) => (
```suggestion
   const enrichResources = (resources) => (
```

While it's technically legal to define without a declaration, it's not a great practice.

2022-09-02 01:10 UTC, zautumnz commented on style.css
> +}
Newline here please

2022-09-02 01:10 UTC, zautumnz commented on style.css
> +  width: -webkit-fill-available;
Does this also need a `-moz-available` or something for FF support?

2022-09-02 01:10 UTC, zautumnz commented on script.js
> +      resList = resources
These two lines could just be `fetchy(resources)`; `resList` is defined without a declaration, and creating the extra variable is useless in this context.

2022-09-02 01:10 UTC, zautumnz commented on script.js
> +    const enrichedResources = enrichResources(resList)
I believe this should be `enrichResources(resources)`; resList isn't defined in this scope except by the global declaration below (see that comment).

2022-09-02 01:10 UTC, zautumnz commented on script.js
> +    const fuse = new window.Fuse(enrichResources(resList), fuseOptions)
No need to call `enrichResources` again, this can just use `enrichedResources`.

2022-09-02 01:10 UTC, zacanger commented on script.js
> +        var completeList = itemsList.concat(items)
`const` please

2022-09-02 01:10 UTC, zacanger commented on script.js
> +    window.onscroll = function(e) {
```suggestion
    window.onscroll = (e) => {
```

2022-09-02 01:10 UTC, zacanger commented on script.js
> +    const itemsList = items.splice(0,15)
```suggestion
    const itemsList = items.slice(0, 15)
```

`splice` mutates the original array, `slice` does not. These splices progressively delete more of the original array. Need to take into account the current index and use a `slice`.

2022-09-02 01:10 UTC, zacanger commented on script.js
> +          itemsList.push(...items.splice(0,15))
```suggestion
          itemsList.push(...items.slice(0, 15))
```

2022-09-02 01:10 UTC, zacanger commented on script.js
> +          $('ul').html(itemsList.concat(resList.splice(0,15)))
```suggestion
          $('ul').html(itemsList.concat(resList.slice(0, 15)))
```

2022-09-02 01:10 UTC, zacanger commented on script.js
> +        addListFilter()
Probably because this is a draft, but calling `addListFilter` inside `addListFilter` won't be good.

2022-09-02 16:50 UTC, m-ox commented on script.js
> +   enrichResources = (resources) => (
absolutely agree

2023-09-10 01:07 UTC, merged

2023-09-10 01:08 UTC, zacanger commented
Thanks for this. I merged it manually, because I'm going to archive this project and wanted your contribution to land first.